# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_scanner.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Scanner(object):
    def setupUi(self, Scanner):
        Scanner.setObjectName("Scanner")
        Scanner.resize(487, 366)
        self.verticalLayout = QtWidgets.QVBoxLayout(Scanner)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Scanner)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout.setObjectName("formLayout")
        self.combScanner = QtWidgets.QComboBox(self.groupBox_3)
        self.combScanner.setObjectName("combScanner")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.combScanner)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.sbWidth = QtWidgets.QSpinBox(self.groupBox)
        self.sbWidth.setMaximum(1000)
        self.sbWidth.setProperty("value", 210)
        self.sbWidth.setObjectName("sbWidth")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sbWidth)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.sbHeight = QtWidgets.QSpinBox(self.groupBox)
        self.sbHeight.setMaximum(1000)
        self.sbHeight.setProperty("value", 297)
        self.sbHeight.setObjectName("sbHeight")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sbHeight)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.sbResolution = QtWidgets.QSpinBox(self.groupBox_2)
        self.sbResolution.setMaximum(10000)
        self.sbResolution.setObjectName("sbResolution")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sbResolution)
        self.combColor = QtWidgets.QComboBox(self.groupBox_2)
        self.combColor.setObjectName("combColor")
        self.combColor.addItem("")
        self.combColor.addItem("")
        self.combColor.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.combColor)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Scanner)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Scanner)
        self.buttonBox.accepted.connect(Scanner.accept) # type: ignore
        self.buttonBox.rejected.connect(Scanner.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Scanner)

    def retranslateUi(self, Scanner):
        _translate = QtCore.QCoreApplication.translate
        Scanner.setWindowTitle(_translate("Scanner", "Select scanner"))
        self.groupBox_3.setTitle(_translate("Scanner", "Scanner"))
        self.groupBox.setTitle(_translate("Scanner", "Size"))
        self.label_2.setText(_translate("Scanner", "Width (mm)"))
        self.label.setText(_translate("Scanner", "Height (mm)"))
        self.groupBox_2.setTitle(_translate("Scanner", "Quality"))
        self.label_4.setText(_translate("Scanner", "Resolution"))
        self.label_3.setText(_translate("Scanner", "Color mode"))
        self.combColor.setItemText(0, _translate("Scanner", "Color"))
        self.combColor.setItemText(1, _translate("Scanner", "Gray"))
        self.combColor.setItemText(2, _translate("Scanner", "Lineart"))
